import { Modal } from '../../../components/overlays/Modal';
import { StatusPill, statusClass } from '../../../components/ui/StatusPill';
import type { Customer } from '../types/customer.types';

const initials = (name: string) => name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
const display = (value: string) => value || 'Not provided';

export function CustomerDetailModal({ customer, onClose, onEdit, onViewStatement }: { customer: Customer; onClose: () => void; onEdit?: () => void; onViewStatement: () => void }) {
    return <Modal title={customer.name} eyebrow={`CUSTOMER PROFILE / ${customer.id}`} onClose={onClose} wide>
        <p className="customer-modal-intro">Complete identity, KYC, nominee, service and transaction record.</p>
        <div className="customer-profile-summary"><div className="customer-avatar">{initials(customer.name)}</div><div><strong>{customer.id}</strong><span>{customer.phone} · Registered {customer.registrationDate}</span></div><StatusPill status={customer.status} /></div>
        <div className="customer-detail-grid">
            <div><span>Customer type</span><strong>{customer.customerType}</strong></div><div><span>Branch</span><strong>{display(customer.branch)}</strong></div><div><span>Mobile number</span><strong>{customer.phone}</strong></div><div><span>Email</span><strong>{display(customer.email)}</strong></div>
            <div><span>Alternate phone</span><strong>{display(customer.alternatePhone)}</strong></div><div><span>Date of birth / incorporation</span><strong>{display(customer.dateOfBirth)}</strong></div><div><span>Gender</span><strong>{display(customer.gender)}</strong></div><div><span>Occupation / business</span><strong>{display(customer.occupation || customer.businessType)}</strong></div>
            <div><span>Current address</span><strong>{customer.address}</strong></div><div><span>Permanent address</span><strong>{display(customer.permanentAddress)}</strong></div><div><span>Identity</span><strong>{display(customer.identityType)} · {display(customer.identityReference)}</strong></div><div><span>PAN / tax identifier</span><strong>{display(customer.taxIdentifier)}</strong></div>
            <div><span>KYC verification</span><strong>{customer.kycMethod} · {display(customer.kycVerifiedOn)}</strong></div><div><span>AML risk category</span><strong>{display(customer.amlRiskCategory)}</strong></div><div><span>Source of funds</span><strong>{display(customer.sourceOfFunds)}</strong></div><div><span>Communication preference</span><strong>{display(customer.communicationPreference)}</strong></div>
            <div><span>Nominee</span><strong>{customer.nomineeName} · {customer.nomineeRelation}</strong></div><div><span>Nominee mobile</span><strong>{customer.nomineePhone}</strong></div><div><span>Guardian</span><strong>{display(customer.guardianName)} · {display(customer.guardianPhone)}</strong></div><div><span>Consent captured</span><strong>{customer.consentCaptured ? 'Yes' : 'Not recorded'}</strong></div>
            <div><span>Assigned agent</span><strong>{display(customer.assignedAgent)}</strong></div><div><span>Total value</span><strong>{customer.value || '—'}</strong></div><div><span>Account status</span><strong>{customer.status}</strong></div><div><span>Account summary</span><strong>{display(customer.accountSummary)}</strong></div><div><span>Document references</span><strong>{display(customer.documentReferences)}</strong></div>
        </div>
        <section className="customer-subsection"><div className="customer-section-heading"><div><h3>Active accounts and services</h3><p>Deposit, RD, FD and loan services mapped to this customer.</p></div><span>{customer.services.length} services</span></div>{customer.services.length ? <div className="customer-service-list">{customer.services.map((service) => <div className="customer-service-row" key={service.id}><div><strong>{service.label}</strong><span>{service.accountNumber} · {service.detail}</span></div><div><strong>{service.amount}</strong><span className={statusClass(service.status)}>{service.status}</span></div></div>)}</div> : <div className="empty-state"><strong>No active accounts</strong><span>Account products will appear here after they are linked.</span></div>}</section>
        <section className="customer-subsection"><div className="customer-section-heading"><div><h3>Transaction history</h3><p>Collections, repayments and withdrawal activity for this customer.</p></div><span>{customer.transactions.length} entries</span></div>{customer.transactions.length ? <div className="customer-transaction-list">{customer.transactions.map((transaction) => <div className="customer-transaction-row" key={transaction.id}><div><strong>{transaction.type}</strong><span>{transaction.id} · {transaction.date || 'Date not recorded'} · {display(transaction.agent)}</span></div><div><strong>{transaction.amount}</strong><span>{display(transaction.reference)}</span><span className={statusClass(transaction.status)}>{transaction.status}</span></div></div>)}</div> : <div className="empty-state"><strong>No transactions recorded</strong><span>Financial activity will be retained in this history.</span></div>}</section>
        <div className="customer-detail-actions"><button className="secondary-button" onClick={onViewStatement}>View statement</button>{onEdit && <button className="primary-button" onClick={onEdit}>Edit customer</button>}</div>
    </Modal>;
}
